### ISSUE TITLE
How to define initWidth and initHight properly?

### ISSUE THREAD

**Issue by EllisShen** [Dharmoslap/react-native-responsive-image#12]
Hi,
I have a quick question. In your example, the initWidth and initHight are set to `138`.
I'm wondering how it defined? I'm using your module on Android devices, as you know, Android has so many different resolutions, how do I define a good init value to resize the image?

Thanks,
-Ellis Shen

**Comment by ladas-larry** [comment]
It is because of the scale of the image equals device.width/414. So if I want to put three images on full width, you set image to 414/3 which equals 138.

**Comment by EllisShen** [comment]
I see, thank you @Dharmoslap
