### ISSUE TITLE
Expected string or a class function but got undefined in 2.0.0 for RN 40

### ISSUE THREAD

**Issue by vinceprofeta** [Dharmoslap/react-native-responsive-image#19]
If i remove react-native-responsive-image the error goes away.

![image](https://cloud.githubusercontent.com/assets/1517775/21901737/85881440-d8be-11e6-8902-8e9cee1509c2.png)

**Comment by miigwall** [comment]
It started working when I uncommented
// module.exports = ResponsiveImage;
from "../node_modules/react-native-responsive-image/react-native-responsive-image.js"
https://github.com/react-native-community/react-native-linear-gradient/issues/93
