### ISSUE TITLE
Requiring unknow module "react-native-responsive-image"

### ISSUE THREAD

**Issue by yelkamel** [Dharmoslap/react-native-responsive-image#20]
Hello,

I trying to use your fabulous module on android 4.4 but I got this error:
Requiring unknown module "react-native-responsive-image". If you are sure the module is there, try restarting the packager or running "npm install"

It's work on iOS, maybe I have to install it manually ? how I don't know...

**Comment by yelkamel** [comment]
In the emulator, it's working well.
Maybe it's due to the fact the device have 8 inch...

**Comment by ladas-larry** [comment]
I'm not sure how to reproduce this, but that size of device should not really matter.

**Comment by yelkamel** [comment]
It's from my system sorry.
