### ISSUE TITLE
Allow custom device scales

### ISSUE THREAD

**Issue by ghost** [Dharmoslap/react-native-responsive-image#22]
If it were possible to pass in information that allowed custom device scales to be used as the developer sees fit this would allow them to use this package without cloning the repository into their project if they require different scale values for the task at hand.

If this seems reasonable I can implement it as desired.

Thank you

**Comment by wilomgfx** [comment]
That would be great

**Comment by ladas-larry** [comment]
You are welcome to make PR for this. :)

**Comment by jeaye** [comment]
@calvinmikael Do you have any update on the progress of this?

**Comment by ghost** [comment]
@jeaye I'm not working on this and currently have no plans to work on this.
