### ISSUE TITLE
Using <Image> with children is deprecated

### ISSUE THREAD

**Issue by lhoang-tst** [Dharmoslap/react-native-responsive-image#34]
Passing child components raises the warning message 'Using <Image> with children is deprecated and will be an error in the near future. Please consider the layout or use <ImageBackground> instead.

**Comment by ladas-larry** [comment]
Thanks, I will have a look at this. If you have an idea how to fix it, feel welcome to create PR.

**Comment by ardmn** [comment]
I have same issues, can you see my PR https://github.com/Dharmoslap/react-native-responsive-image/pull/36 ?

**Comment by ladas-larry** [comment]
Merged and released.
