### ISSUE TITLE
Circle Image

### ISSUE THREAD

**Issue by dhamdani666** [Dharmoslap/react-native-responsive-image#35]
how to create circle image with this package ?

**Comment by blake-simpson** [comment]
@dhamdani666 All props get delegated to the original RN `<Image />` so you can pass a style to it with a `borderRadius` that is half of the image size. For Android you should also pass a `borderRadius` prop, if the image has children.

Something like: 

```
const imgStyles = {width: 50, height: 50, borderRadius: 25};
<ResponsiveImage source={...} style={imgStyles} borderRadius={25} />
```

**Comment by dhamdani666** [comment]
I've tried but doesn't work but now work with the code you provide.
thank
