### ISSUE TITLE
Add prop that sets ImageBackground or Image

### ISSUE THREAD

**Issue by chops318** [Dharmoslap/react-native-responsive-image#38]
Love the repo, but I am using images that require resizeMode: 'contain' and it seems the ImageBackground component does not accept that. Would it make sense for those of us not using ImageBackground, but needing Image (not sure what other props differ between the two). I'd be happy to but together a PR if you'd like

**Comment by ladas-larry** [comment]
That's a good idea. Feel free to open PR for this and I will merge it.

**Comment by chops318** [comment]
What do you think would be a better API for this

`<ResponsiveImage type={'image'} />` and `<ResponsiveImage type={'imageBackground'} />` 

or just `<ResponsiveImage imageBackground={false}` and short circuiting the prop to true if not supplied. Any suggestions?

**Comment by ladas-larry** [comment]
Best would to optianally pass wrapping componet, like this:
```
import { ImageBackground } from 'react-native'
<ResponsiveImage componet={ImageBackground} />
```

**Comment by chops318** [comment]
Makes sense, i'll have make the PR this weekend. Thanks

**Comment by ladas-larry** [comment]
I will merge it when you are ready.

**Comment by chops318** [comment]
Submitted the PR, should I close this thread?

**Comment by ladas-larry** [comment]
Yes, you can close it, I will release today.
