### ISSUE TITLE
compatibility with 0.19

### ISSUE THREAD

**Issue by thedgbrt** [Dharmoslap/react-native-responsive-image#5]
Or am I missing something ? Thanks for the great work :+1: 

```
npm ERR! peerinvalid The package react-native@0.19.0 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer react-native-responsive-image@1.1.2 wants react-native@0.17.x
```

**Comment by zxcpoiu** [comment]
I use npm3 and have the same problem.
But after  `npm install`, there DID have files installed in my `node_module` directory.

I just find this module, and edit it's package.json to:

```
  "peerDependencies": {
    "react-native": "0.19.x"
  },
```

And it just work.
I don't know if this module already support RN 0.19, if yes, then just modify package.json.

**Comment by ladas-larry** [comment]
Fixed in new release
