### ISSUE TITLE
Publish Latest to NPM

### ISSUE THREAD

**Issue by browniefed** [Dharmoslap/react-native-responsive-image#6]
Hey if you wouldn't mind publishing 1.1.3 to NPM that'd be appreciated.

Also removing `peerDependencies` would also be awesome. Having `peerDependencies` just causes a tremendous amount of issues for everyone involved.

**Comment by ladas-larry** [comment]
I see, can you please explain what kind of troubles with peerDependencies do you mean?

**Comment by browniefed** [comment]
If you do not specify the specific dependency or greater than a specific dependency version then you will be unable to install and upgrade to the latest react-native version (easily). 

Additionally this won't work with `-rc` versions unless you specifically call them out. Granted with NPM3 peerDependencies aren't auto-installed which is great, but in NPM2 they are. You could get into situations with multiple react-native versions, etc.

Here is a quick twitter thread https://twitter.com/ryanflorence/status/643474735385309184

All in all peer dependencies for React Native, and especially for libraries that aren't actually bridging anything (like react-native-responsive-image) just cause a major headache for developers.

**Comment by browniefed** [comment]
Additionally .20 was just released, you now have to update and publish. Your library still works on older versions though, you are now forcing people to use a very specific version of react-native even though it works with I believe every version of react native

**Comment by jayesbe** [comment]
Would be nice to have this published
